name: Verify Built Files

on:
  - pull_request
  - push

env:
  SCRIPT_NAME: build

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm ci || npm install
      - run: npm run ${{ env.SCRIPT_NAME }}
      - name: verify that distribution/index.js is up to date
        run: git diff --exit-code
