name: CI

on:
  - pull_request
  - push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: if [ -z ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json') }} ]; then npm install; else npm ci; fi;
      - name: AVA
        run: npx ava
