name: Verify Built Files

on:
  - pull_request
  - push

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci || npm install
        name: install
      - run: npm run build
      - run: git diff --exit-code
        name: verify that distribution/index.js is up to date
